site_name: Conia Wire
copyright: © 2023-2024 ebene fünf GmbH
nav:
  - Documentation:
    - index.md
    - creator.md
    - resolvers.md
    - container.md
    - call-attribute.md
    - inject-attribute.md
  - Resources:
    - changelog.md
    - license.md
theme:
    name: conia
repo_url: https://github.com/coniadev/wire
extra:
    project: Wire
plugins:
    - search
    - macros:
        module_name: docs/main
markdown_extensions:
    - admonition
    - pymdownx.snippets:
        base_path: [".", "docs/code"]
