site_name: Conia Wire
copyright: © 2023 ebene fünf GmbH
nav:
  - index.md
  - container.md
  - call-attribute.md
  - inject-attribute.md
  - callables.md
theme:
    name: conia
repo_url: https://github.com/coniadev/wire
extra:
    project: Wire
plugins:
    - search
    - macros:
        module_name: docs/main
markdown_extensions:
    - pymdownx.snippets:
        base_path: ["docs/code"]
